"""create king table

Revision ID: a338f48b8392
Revises: 
Create Date: 2024-12-30 14:41:12.599040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a338f48b8392'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('king',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nick', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nick')
    )
    op.create_table('station',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('uri', sa.Text(), nullable=False),
    sa.Column('location_id', sa.String(length=255), nullable=False),
    sa.Column('king_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['king_id'], ['king.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('fuel_type', sa.String(), nullable=True),
    sa.Column('king_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['king_id'], ['king.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['station_id'], ['station.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('king_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('review', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['king_id'], ['king.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['station_id'], ['station.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    op.drop_table('price')
    op.drop_table('station')
    op.drop_table('king')
    # ### end Alembic commands ###
